# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'action_dialog_2.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ActionDialog(object):
    def setupUi(self, ActionDialog):
        ActionDialog.setObjectName("ActionDialog")
        ActionDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        ActionDialog.resize(516, 223)
        self.gridLayout = QtWidgets.QGridLayout(ActionDialog)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_1 = QtWidgets.QWidget(ActionDialog)
        self.widget_1.setStyleSheet("#widget_1{background-color: qlineargradient(spread:pad, x1:0, y1:0.625, x2:1, y2:0.955, stop:0 rgba(71, 130, 178, 255), stop:0.493943 rgba(92, 153, 202, 255), stop:0.991925 rgba(126, 188, 238, 255), stop:0.997308 rgba(214, 227, 238, 255), stop:1 rgba(214, 227, 238, 255));} QLabel{color : #ffffff;}")
        self.widget_1.setObjectName("widget_1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_1)
        self.gridLayout_3.setContentsMargins(-1, 5, -1, 5)
        self.gridLayout_3.setVerticalSpacing(2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_action = QtWidgets.QLabel(self.widget_1)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.label_action.setFont(font)
        self.label_action.setText("Done")
        self.label_action.setAlignment(QtCore.Qt.AlignCenter)
        self.label_action.setObjectName("label_action")
        self.gridLayout_3.addWidget(self.label_action, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget_1)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setText("Failed")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget_1)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setText("Not Allowed")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.widget_1)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.label_8.setFont(font)
        self.label_8.setText("Ignored")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 0, 3, 1, 1)
        self.label_done = QtWidgets.QLabel(self.widget_1)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.label_done.setFont(font)
        self.label_done.setText("0")
        self.label_done.setAlignment(QtCore.Qt.AlignCenter)
        self.label_done.setObjectName("label_done")
        self.gridLayout_3.addWidget(self.label_done, 1, 0, 1, 1)
        self.label_failed = QtWidgets.QLabel(self.widget_1)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.label_failed.setFont(font)
        self.label_failed.setText("0")
        self.label_failed.setAlignment(QtCore.Qt.AlignCenter)
        self.label_failed.setObjectName("label_failed")
        self.gridLayout_3.addWidget(self.label_failed, 1, 1, 1, 1)
        self.label_notAllowed = QtWidgets.QLabel(self.widget_1)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.label_notAllowed.setFont(font)
        self.label_notAllowed.setText("0")
        self.label_notAllowed.setAlignment(QtCore.Qt.AlignCenter)
        self.label_notAllowed.setObjectName("label_notAllowed")
        self.gridLayout_3.addWidget(self.label_notAllowed, 1, 2, 1, 1)
        self.label_ignored = QtWidgets.QLabel(self.widget_1)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.label_ignored.setFont(font)
        self.label_ignored.setText("0")
        self.label_ignored.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ignored.setObjectName("label_ignored")
        self.gridLayout_3.addWidget(self.label_ignored, 1, 3, 1, 1)
        self.gridLayout.addWidget(self.widget_1, 0, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(ActionDialog)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_4.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.progressBar = QtWidgets.QProgressBar(self.widget_2)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_4.addWidget(self.progressBar, 1, 0, 1, 2)
        self.stackedWidget = QtWidgets.QStackedWidget(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.page_1)
        self.gridLayout_5.setContentsMargins(4, 4, 4, 4)
        self.gridLayout_5.setSpacing(4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_9 = QtWidgets.QLabel(self.page_1)
        self.label_9.setText("From :")
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 0, 0, 1, 1)
        self.label_fromDir = QtWidgets.QLabel(self.page_1)
        self.label_fromDir.setObjectName("label_fromDir")
        self.gridLayout_5.addWidget(self.label_fromDir, 0, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.page_1)
        self.label_10.setText("Destination :")
        self.label_10.setObjectName("label_10")
        self.gridLayout_5.addWidget(self.label_10, 1, 0, 1, 1)
        self.label_desDir = QtWidgets.QLabel(self.page_1)
        self.label_desDir.setObjectName("label_desDir")
        self.gridLayout_5.addWidget(self.label_desDir, 1, 1, 1, 1)
        self.label_action_going = QtWidgets.QLabel(self.page_1)
        self.label_action_going.setObjectName("label_action_going")
        self.gridLayout_5.addWidget(self.label_action_going, 2, 0, 1, 1)
        self.label_file = QtWidgets.QLabel(self.page_1)
        self.label_file.setObjectName("label_file")
        self.gridLayout_5.addWidget(self.label_file, 2, 1, 1, 1)
        self.gridLayout_5.setColumnStretch(0, 1)
        self.gridLayout_5.setColumnStretch(1, 4)
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_statBar = QtWidgets.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_statBar.setFont(font)
        self.label_statBar.setObjectName("label_statBar")
        self.gridLayout_6.addWidget(self.label_statBar, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.gridLayout_4.addWidget(self.stackedWidget, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.widget_2, 1, 0, 1, 1)
        self.widget_3 = QtWidgets.QWidget(ActionDialog)
        self.widget_3.setStyleSheet("#widget_3{background-color: rgb(231, 231, 231);}")
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_2.setContentsMargins(15, -1, 15, -1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 0, 1, 1)
        self.pushButton_start = QtWidgets.QPushButton(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_start.setFont(font)
        self.pushButton_start.setText("Start")
        self.pushButton_start.setObjectName("pushButton_start")
        self.gridLayout_2.addWidget(self.pushButton_start, 0, 1, 1, 1)
        self.pushButton_finish = QtWidgets.QPushButton(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_finish.setFont(font)
        self.pushButton_finish.setText("Finish")
        self.pushButton_finish.setObjectName("pushButton_finish")
        self.gridLayout_2.addWidget(self.pushButton_finish, 0, 3, 1, 1)
        self.pushButton_cancel = QtWidgets.QPushButton(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_cancel.setFont(font)
        self.pushButton_cancel.setText("Cancel")
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.gridLayout_2.addWidget(self.pushButton_cancel, 0, 2, 1, 1)
        self.gridLayout.addWidget(self.widget_3, 2, 0, 1, 1)
        self.gridLayout.setRowStretch(0, 2)
        self.gridLayout.setRowStretch(1, 3)
        self.gridLayout.setRowStretch(2, 1)

        self.retranslateUi(ActionDialog)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(ActionDialog)
        ActionDialog.setTabOrder(self.pushButton_start, self.pushButton_cancel)
        ActionDialog.setTabOrder(self.pushButton_cancel, self.pushButton_finish)

    def retranslateUi(self, ActionDialog):
        pass

