from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(510, 494)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.main_grid = QtWidgets.QGridLayout()
        self.main_grid.setObjectName("main_grid")
        self.side_layout = QtWidgets.QWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.side_layout.setFont(font)
        self.side_layout.setStyleSheet("#side_layout{background: rgb(230, 231, 255);}")
        self.side_layout.setObjectName("side_layout")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.side_layout)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.formLayout_8 = QtWidgets.QFormLayout()
        self.formLayout_8.setObjectName("formLayout_8")
        self.label_46 = QtWidgets.QLabel(self.side_layout)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_46.setFont(font)
        self.label_46.setToolTip("<html><head/><body><p>Here, you can find <span style=\" font-weight:600;\">settings</span> for selecting only those file which are <span style=\" font-weight:600;\">allowed</span>. Leave any option <span style=\" font-weight:600;\">blank</span> if you do not need them.</p></body></html>")
        self.label_46.setText("Only Allow Files")
        self.label_46.setAlignment(QtCore.Qt.AlignCenter)
        self.label_46.setObjectName("label_46")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_46)
        self.label_51 = QtWidgets.QLabel(self.side_layout)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_51.setFont(font)
        self.label_51.setToolTip("<html><head/><body><p>If you <span style=\" font-weight:600;\">enable</span> it and change any setting bellow, <span style=\" font-weight:600;\">only allow system</span> will work. If a file is <span style=\" font-weight:600;\">not allowed</span>, it will not be <span style=\" font-weight:600;\">selected</span>.</p></body></html>")
        self.label_51.setText("Enabled :")
        self.label_51.setObjectName("label_51")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_51)
        self.side_input_2 = QtWidgets.QCheckBox(self.side_layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.side_input_2.sizePolicy().hasHeightForWidth())
        self.side_input_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.side_input_2.setFont(font)
        self.side_input_2.setText("")
        self.side_input_2.setCheckable(True)
        self.side_input_2.setObjectName("side_input_2")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.side_input_2)
        self.widget_0_1 = QtWidgets.QWidget(self.side_layout)
        self.widget_0_1.setEnabled(False)
        self.widget_0_1.setObjectName("widget_0_1")
        self.formLayout = QtWidgets.QFormLayout(self.widget_0_1)
        self.formLayout.setContentsMargins(0, 3, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_44 = QtWidgets.QLabel(self.widget_0_1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_44.setFont(font)
        self.label_44.setToolTip("<html><head/><body><p><span style=\" font-weight:600;\">Check</span> it, if you want to <span style=\" font-weight:600;\">allow</span> only those file which <span style=\" font-weight:600;\">does not </span>have any <span style=\" font-weight:600;\">extension</span>.</p></body></html>")
        self.label_44.setText("With no ext : ")
        self.label_44.setObjectName("label_44")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_44)
        self.side_input_3 = QtWidgets.QCheckBox(self.widget_0_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.side_input_3.sizePolicy().hasHeightForWidth())
        self.side_input_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.side_input_3.setFont(font)
        self.side_input_3.setText("")
        self.side_input_3.setCheckable(True)
        self.side_input_3.setObjectName("side_input_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.side_input_3)
        self.gridLayout_20 = QtWidgets.QGridLayout()
        self.gridLayout_20.setHorizontalSpacing(0)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.label_55 = QtWidgets.QLabel(self.widget_0_1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_55.setFont(font)
        self.label_55.setToolTip("<html><head/><body><p>Use it, if you want to <span style=\" font-weight:600;\">allow</span> only those file which have any of the following <span style=\" font-weight:600;\">extension</span>.</p><p>Here you can set <span style=\" font-weight:600;\">more than one</span> extension by putting <span style=\" font-weight:600;\">&quot;|&quot;(Pipe) </span>between them.</p></body></html>")
        self.label_55.setText("With ext : ")
        self.label_55.setObjectName("label_55")
        self.gridLayout_20.addWidget(self.label_55, 0, 0, 1, 1)
        self.side_input_4 = QtWidgets.QLineEdit(self.widget_0_1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.side_input_4.setFont(font)
        self.side_input_4.setObjectName("side_input_4")
        self.gridLayout_20.addWidget(self.side_input_4, 0, 1, 1, 1)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.SpanningRole, self.gridLayout_20)
        self.label_54 = QtWidgets.QLabel(self.widget_0_1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_54.setFont(font)
        self.label_54.setToolTip("<html><head/><body><p>Use it, if you want to <span style=\" font-weight:600;\">allow</span> only those file which have any of the following <span style=\" font-weight:600;\">text </span>on the <span style=\" font-weight:600;\">start</span> of the filename (without extension).</p><p>Here you can set <span style=\" font-weight:600;\">more than one</span> text by putting <span style=\" font-weight:600;\">&quot;|&quot;(Pipe) </span>between them.</p></body></html>")
        self.label_54.setText("Has on start  : ")
        self.label_54.setObjectName("label_54")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_54)
        self.side_input_5 = QtWidgets.QLineEdit(self.widget_0_1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.side_input_5.setFont(font)
        self.side_input_5.setObjectName("side_input_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.side_input_5)
        self.label_53 = QtWidgets.QLabel(self.widget_0_1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_53.setFont(font)
        self.label_53.setToolTip("<html><head/><body><p>Use it, if you want to <span style=\" font-weight:600;\">allow</span> only those file which have any of the following <span style=\" font-weight:600;\">text </span>on the <span style=\" font-weight:600;\">end</span> of the filename (without extension).</p><p>Here you can set <span style=\" font-weight:600;\">more than one</span> text by putting <span style=\" font-weight:600;\">&quot;|&quot;(Pipe) </span>between them.</p></body></html>")
        self.label_53.setText("Has on end  : ")
        self.label_53.setObjectName("label_53")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_53)
        self.side_input_6 = QtWidgets.QLineEdit(self.widget_0_1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.side_input_6.setFont(font)
        self.side_input_6.setObjectName("side_input_6")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.side_input_6)
        self.label_52 = QtWidgets.QLabel(self.widget_0_1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_52.setFont(font)
        self.label_52.setToolTip("<html><head/><body><p>Use it, if you want to <span style=\" font-weight:600;\">allow</span> only those file which have any of the following <span style=\" font-weight:600;\">text </span>in the filename (without extension).</p><p>Here you can set <span style=\" font-weight:600;\">more than one</span> text by putting <span style=\" font-weight:600;\">&quot;|&quot;(Pipe) </span>between them.</p></body></html>")
        self.label_52.setText("Has string  : ")
        self.label_52.setObjectName("label_52")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_52)
        self.side_input_7 = QtWidgets.QLineEdit(self.widget_0_1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.side_input_7.setFont(font)
        self.side_input_7.setObjectName("side_input_7")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.side_input_7)
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.widget_0_1)
        self.gridLayout_3.addLayout(self.formLayout_8, 2, 0, 1, 1)
        self.formLayout_7 = QtWidgets.QFormLayout()
        self.formLayout_7.setObjectName("formLayout_7")
        self.label_41 = QtWidgets.QLabel(self.side_layout)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_41.setFont(font)
        self.label_41.setToolTip("<html><head/><body><p>Here, you can find <span style=\" font-weight:600;\">settings</span> for ignoring a file. Leave any option <span style=\" font-weight:600;\">blank</span> if you do not need them.</p></body></html>")
        self.label_41.setText("Ignore Files")
        self.label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41.setObjectName("label_41")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_41)
        self.label_56 = QtWidgets.QLabel(self.side_layout)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_56.setFont(font)
        self.label_56.setToolTip("<html><head/><body><p>If you <span style=\" font-weight:600;\">enable</span> it and change any setting bellow,<span style=\" font-weight:600;\"> ignore system</span> will work. If a file is <span style=\" font-weight:600;\">ignored</span>, it wiil not be <span style=\" font-weight:600;\">selected</span>.</p></body></html>")
        self.label_56.setText("Enabled :")
        self.label_56.setObjectName("label_56")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_56)
        self.side_input_8 = QtWidgets.QCheckBox(self.side_layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.side_input_8.sizePolicy().hasHeightForWidth())
        self.side_input_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.side_input_8.setFont(font)
        self.side_input_8.setText("")
        self.side_input_8.setCheckable(True)
        self.side_input_8.setObjectName("side_input_8")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.side_input_8)
        self.widget_0_2 = QtWidgets.QWidget(self.side_layout)
        self.widget_0_2.setEnabled(False)
        self.widget_0_2.setObjectName("widget_0_2")
        self.formLayout_5 = QtWidgets.QFormLayout(self.widget_0_2)
        self.formLayout_5.setContentsMargins(0, 3, 0, 0)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_42 = QtWidgets.QLabel(self.widget_0_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_42.setFont(font)
        self.label_42.setToolTip("<html><head/><body><p><span style=\" font-weight:600;\">Check</span> it, if you want to <span style=\" font-weight:600;\">ignore</span> those file which <span style=\" font-weight:600;\">does not </span>have any <span style=\" font-weight:600;\">extension</span>.</p></body></html>")
        self.label_42.setText("With no ext : ")
        self.label_42.setObjectName("label_42")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_42)
        self.side_input_9 = QtWidgets.QCheckBox(self.widget_0_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.side_input_9.sizePolicy().hasHeightForWidth())
        self.side_input_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.side_input_9.setFont(font)
        self.side_input_9.setText("")
        self.side_input_9.setCheckable(True)
        self.side_input_9.setObjectName("side_input_9")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.side_input_9)
        self.gridLayout_18 = QtWidgets.QGridLayout()
        self.gridLayout_18.setHorizontalSpacing(0)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.label_43 = QtWidgets.QLabel(self.widget_0_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_43.setFont(font)
        self.label_43.setToolTip("<html><head/><body><p>Use it, if you want to <span style=\" font-weight:600;\">ignore</span> those file which have any of the following <span style=\" font-weight:600;\">extension</span>.</p><p>Here you can set <span style=\" font-weight:600;\">more than one</span> extension by putting <span style=\" font-weight:600;\">&quot;|&quot;(Pipe) </span>between them.</p></body></html>")
        self.label_43.setText("With ext : ")
        self.label_43.setObjectName("label_43")
        self.gridLayout_18.addWidget(self.label_43, 0, 0, 1, 1)
        self.side_input_10 = QtWidgets.QLineEdit(self.widget_0_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.side_input_10.setFont(font)
        self.side_input_10.setObjectName("side_input_10")
        self.gridLayout_18.addWidget(self.side_input_10, 0, 1, 1, 1)
        self.formLayout_5.setLayout(1, QtWidgets.QFormLayout.SpanningRole, self.gridLayout_18)
        self.label_47 = QtWidgets.QLabel(self.widget_0_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_47.setFont(font)
        self.label_47.setToolTip("<html><head/><body><p>Use it, if you want to <span style=\" font-weight:600;\">ignore</span> those file which have any of the following <span style=\" font-weight:600;\">text </span>on the <span style=\" font-weight:600;\">start</span> of the filename (without extension).</p><p>Here you can set <span style=\" font-weight:600;\">more than one</span> text by putting <span style=\" font-weight:600;\">&quot;|&quot;(Pipe) </span>between them.</p></body></html>")
        self.label_47.setText("Has on start  : ")
        self.label_47.setObjectName("label_47")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_47)
        self.side_input_11 = QtWidgets.QLineEdit(self.widget_0_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.side_input_11.setFont(font)
        self.side_input_11.setObjectName("side_input_11")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.side_input_11)
        self.label_48 = QtWidgets.QLabel(self.widget_0_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_48.setFont(font)
        self.label_48.setToolTip("<html><head/><body><p>Use it, if you want to <span style=\" font-weight:600;\">ignore</span> those file which have any of the following <span style=\" font-weight:600;\">text </span>on the <span style=\" font-weight:600;\">end</span> of the filename (without extension).</p><p>Here you can set <span style=\" font-weight:600;\">more than one</span> text by putting <span style=\" font-weight:600;\">&quot;|&quot;(Pipe) </span>between them.</p></body></html>")
        self.label_48.setText("Has on end  : ")
        self.label_48.setObjectName("label_48")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_48)
        self.side_input_12 = QtWidgets.QLineEdit(self.widget_0_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.side_input_12.setFont(font)
        self.side_input_12.setObjectName("side_input_12")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.side_input_12)
        self.label_49 = QtWidgets.QLabel(self.widget_0_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_49.setFont(font)
        self.label_49.setToolTip("<html><head/><body><p>Use it, if you want to <span style=\" font-weight:600;\">ignore</span> those file which have any of the following <span style=\" font-weight:600;\">text </span>in the filename (without extension).</p><p>Here you can set <span style=\" font-weight:600;\">more than one</span> text by putting <span style=\" font-weight:600;\">&quot;|&quot;(Pipe) </span>between them.</p></body></html>")
        self.label_49.setText("Has string  : ")
        self.label_49.setObjectName("label_49")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_49)
        self.side_input_13 = QtWidgets.QLineEdit(self.widget_0_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.side_input_13.setFont(font)
        self.side_input_13.setObjectName("side_input_13")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.side_input_13)
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.widget_0_2)
        self.gridLayout_3.addLayout(self.formLayout_7, 3, 0, 1, 1)
        self.main_grid.addWidget(self.side_layout, 0, 0, 1, 1)
        self.main_layout = QtWidgets.QWidget(self.centralwidget)
        self.main_layout.setStyleSheet("#main_layout{background: rgb(248, 231, 255);}")
        self.main_layout.setObjectName("main_layout")
        self.gridLayout = QtWidgets.QGridLayout(self.main_layout)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout.setObjectName("gridLayout")
        self.rn_layout_1 = QtWidgets.QWidget(self.main_layout)
        self.rn_layout_1.setStyleSheet("")
        self.rn_layout_1.setObjectName("rn_layout_1")
        self.gridLayout_1 = QtWidgets.QGridLayout(self.rn_layout_1)
        self.gridLayout_1.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout_1.setContentsMargins(4, -1, 4, 0)
        self.gridLayout_1.setObjectName("gridLayout_1")
        self.bt_go = QtWidgets.QPushButton(self.rn_layout_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_go.sizePolicy().hasHeightForWidth())
        self.bt_go.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Andalus")
        font.setPointSize(16)
        self.bt_go.setFont(font)
        self.bt_go.setText("Go")
        self.bt_go.setObjectName("bt_go")
        self.gridLayout_1.addWidget(self.bt_go, 5, 0, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.rn_layout_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setText("Please, complete this form")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_1.addWidget(self.label_3, 1, 0, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.rn_layout_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setText("Directory to File")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_1.addWidget(self.label_4, 0, 0, 1, 2)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setContentsMargins(-1, 15, -1, -1)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_1 = QtWidgets.QLabel(self.rn_layout_1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_1.setFont(font)
        self.label_1.setToolTip("<html><head/><body><p><span style=\" font-weight:600;\">Select</span> your <span style=\" font-weight:600;\">work</span> from here.</p></body></html>")
        self.label_1.setText("Action  : ")
        self.label_1.setObjectName("label_1")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_1)
        self.input_1 = QtWidgets.QComboBox(self.rn_layout_1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_1.setFont(font)
        self.input_1.setCurrentText("Copy")
        self.input_1.setObjectName("input_1")
        self.input_1.addItem("")
        self.input_1.setItemText(0, "Copy")
        self.input_1.addItem("")
        self.input_1.setItemText(1, "Move")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.input_1)
        self.label_2 = QtWidgets.QLabel(self.rn_layout_1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setToolTip("<html><head/><body><p>Place here the <span style=\" font-weight:600;\">output folder</span> for your <span style=\" font-weight:600;\">files</span>.</p></body></html>")
        self.label_2.setText("Output : ")
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.input_2 = QtWidgets.QLineEdit(self.rn_layout_1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.input_2.setFont(font)
        self.input_2.setObjectName("input_2")
        self.gridLayout_2.addWidget(self.input_2, 0, 0, 1, 1)
        self.output_bt = QtWidgets.QToolButton(self.rn_layout_1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.output_bt.setFont(font)
        self.output_bt.setText("...")
        self.output_bt.setObjectName("output_bt")
        self.gridLayout_2.addWidget(self.output_bt, 0, 1, 1, 1)
        self.formLayout_2.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.gridLayout_2)
        self.gridLayout_1.addLayout(self.formLayout_2, 2, 0, 1, 2)
        self.txt_stat = QtWidgets.QLabel(self.rn_layout_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_stat.sizePolicy().hasHeightForWidth())
        self.txt_stat.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txt_stat.setFont(font)
        self.txt_stat.setAcceptDrops(True)
        self.txt_stat.setToolTip("<html><head/><body><p>Here, you will see the <span style=\" font-weight:600;\">current number</span> of the<span style=\" font-weight:600;\"> selected folders</span>. You can also <span style=\" font-weight:600;\">drag</span> your <span style=\" font-weight:600;\">folders</span> here to select.</p></body></html>")
        self.txt_stat.setStyleSheet("QLabel{background-color: rgb(234, 255, 238); border: 1px solid gray; padding: 5px;}")
        self.txt_stat.setText("Drag Your Folders Here")
        self.txt_stat.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_stat.setObjectName("txt_stat")
        self.gridLayout_1.addWidget(self.txt_stat, 4, 0, 1, 2)
        self.side_input_1 = QtWidgets.QCheckBox(self.rn_layout_1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.side_input_1.setFont(font)
        self.side_input_1.setText("")
        self.side_input_1.setCheckable(True)
        self.side_input_1.setObjectName("side_input_1")
        self.gridLayout_1.addWidget(self.side_input_1, 3, 1, 1, 1)
        self.label_58 = QtWidgets.QLabel(self.rn_layout_1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_58.setFont(font)
        self.label_58.setToolTip("<html><head/><body><p>If you <span style=\" font-weight:600;\">check</span> it, all the <span style=\" font-weight:600;\">folders</span> under the <span style=\" font-weight:600;\">selected folders</span> will be also <span style=\" font-weight:600;\">selected</span>.</p></body></html>")
        self.label_58.setText("Include Subfolders : ")
        self.label_58.setObjectName("label_58")
        self.gridLayout_1.addWidget(self.label_58, 3, 0, 1, 1)
        self.gridLayout_1.setRowStretch(0, 1)
        self.gridLayout.addWidget(self.rn_layout_1, 0, 0, 1, 1)
        self.main_grid.addWidget(self.main_layout, 0, 1, 1, 1)
        self.main_grid.setColumnStretch(0, 6)
        self.main_grid.setColumnStretch(1, 10)
        self.horizontalLayout.addLayout(self.main_grid)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 510, 21))
        self.menubar.setObjectName("menubar")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setTitle("About")
        self.menuAbout.setObjectName("menuAbout")
        self.menuTool = QtWidgets.QMenu(self.menubar)
        self.menuTool.setTitle("Tool")
        self.menuTool.setObjectName("menuTool")
        self.menuDirToFile = QtWidgets.QMenu(self.menubar)
        self.menuDirToFile.setTitle("DirToFile")
        self.menuDirToFile.setObjectName("menuDirToFile")
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setWindowTitle("Toolbar")
        self.toolBar.setMovable(False)
        self.toolBar.setIconSize(QtCore.QSize(28, 28))
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionReset_1 = QtWidgets.QAction(MainWindow)
        self.actionReset_1.setText("Reset")
        self.actionReset_1.setObjectName("actionReset_1")
        self.actionExit_1 = QtWidgets.QAction(MainWindow)
        self.actionExit_1.setText("Exit")
        self.actionExit_1.setObjectName("actionExit_1")
        self.actionAbout_the_Author = QtWidgets.QAction(MainWindow)
        self.actionAbout_the_Author.setText("About the Author")
        self.actionAbout_the_Author.setObjectName("actionAbout_the_Author")
        self.actionAdd = QtWidgets.QAction(MainWindow)
        self.actionAdd.setText("Add")
        self.actionAdd.setToolTip("Add a Folder")
        self.actionAdd.setObjectName("actionAdd")
        self.actionClear = QtWidgets.QAction(MainWindow)
        self.actionClear.setText("Clear All")
        self.actionClear.setToolTip("Clear all selected folders")
        self.actionClear.setObjectName("actionClear")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setText("Exit")
        self.actionExit.setObjectName("actionExit")
        self.actionReset = QtWidgets.QAction(MainWindow)
        self.actionReset.setText("Reset")
        self.actionReset.setObjectName("actionReset")
        self.actionAdd_1 = QtWidgets.QAction(MainWindow)
        self.actionAdd_1.setText("Add a Folder")
        self.actionAdd_1.setObjectName("actionAdd_1")
        self.actionClear_1 = QtWidgets.QAction(MainWindow)
        self.actionClear_1.setText("Clear All Folders")
        self.actionClear_1.setObjectName("actionClear_1")
        self.actionAdd_Multiple_Folder = QtWidgets.QAction(MainWindow)
        self.actionAdd_Multiple_Folder.setText("Add Multiple Folder")
        self.actionAdd_Multiple_Folder.setObjectName("actionAdd_Multiple_Folder")
        self.menuAbout.addAction(self.actionAbout_the_Author)
        self.menuTool.addAction(self.actionAdd_1)
        self.menuTool.addAction(self.actionAdd_Multiple_Folder)
        self.menuTool.addSeparator()
        self.menuTool.addAction(self.actionClear_1)
        self.menuDirToFile.addAction(self.actionReset_1)
        self.menuDirToFile.addSeparator()
        self.menuDirToFile.addAction(self.actionExit_1)
        self.menubar.addAction(self.menuDirToFile.menuAction())
        self.menubar.addAction(self.menuTool.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionAdd)
        self.toolBar.addAction(self.actionClear)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionReset)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionExit)

        self.side_input_2.toggled['bool'].connect(self.widget_0_1.setEnabled)
        self.side_input_8.toggled['bool'].connect(self.widget_0_2.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
